### ISSUE TITLE
AuthenticationFailedException when trying to log in to Newsblur

### ISSUE THREAD

**Issue by tomhoward87** [nayfield/GrazeTen#19] opened 2020-05-20 07:48 UTC
Since last night I've been getting an authentication error when trying to log into Newsblur - clearing cache etc didn't seem to help. Unfortunately I can't easily copy paste logs but here is a snippet:

05-20 08:39:43.548 D/com.newsblur.network.APIClient(15461): API POST http://newsblur.com/api/login
05-20 08:39:43.784 W/System.err(15461): com.grazeten.AuthenticationFailedException: 
05-20 08:39:43.788 W/System.err(15461): 	at com.grazeten.EntryManager.doLogin(EntryManager.java:731)
05-20 08:39:43.788 W/System.err(15461): 	at com.grazeten.activities.LoginActivity$LoginTask.doInBackground(LoginActivity.java:63)

**Comment by EDIflyer** [comment] 2020-05-20 08:05
I'm not getting an error but sync isn't working for me either, just click the button, spins and stops almost immediately. Presumably same issue. Signed in to Newsblur website and have 53 stories unread so definitely stuff ready to sync...

**Comment by tomhoward87** [comment] 2020-05-20 08:17
Yes, that's how it started for me, then I tried logging out and back in to see if that fixed it, which is when I saw the error.

**Comment by dgbustos** [comment] 2020-05-20 19:30
It looks like the app makes `http` requests, but Newsblur fails them with a redirect to the `https` version.  It probably started doing that within the last day.  The fix may be as simple as changing the `http` URLs to `https`.

**Comment by nayfield** [comment] 2020-05-20 19:47
It is fixed. Newsblur switched to https only last night and rolled that
back for us.

I hope to have an update out in the next day or so which will let Samuel
undo his revert

**Comment by tomhoward87** [comment] 2020-05-20 20:10
Awesome, thanks!

**Comment by nayfield** [comment] 2020-05-22 22:34
I will leave this open until the fix is reviewed and published to the main play store.  I published it about an hour ago, and they are saying reviews could be up to 7 days due to COVID-19.  

If anybody wants to install the fix early, please contact me (email is on the play store page for GrazeTen) and I can send you a link to join the test channel which has 3.1.6 now.

**Comment by nayfield** [comment] 2020-08-02 00:27
This was confirmed fixed by users and self testing.

**Closed as completed by nayfield** 2020-08-02 00:27 UTC
